name: E2E Test
on:
  push:
    branches:    
      - main
  pull_request:
jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress.io
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
          headless: true
          record: false
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 180
        # env:
          # pass the Dashboard record key as an environment variable
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
